// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microting.RebusPOC.Infrastructure.DB;

namespace Microting.RebusPOC.Infrastructure.migrations.slave
{
    [DbContext(typeof(SlaveDbContext))]
    partial class SlaveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microting.RebusPOC.Infrastructure.DB.Record", b =>
                {
                    b.Property<string>("WorkId")
                        .HasColumnType("varchar(767)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("WorkId");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
